language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  global:
     LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
  matrix:
  - TOXENV=py26,coveralls
  - TOXENV=py27,coveralls
  - TOXENV=py34,coveralls
  - TOXENV=pypy,coveralls
  - TOXENV=docs
    exclude:
    - python: "2.6"
      env: TOXENV=py27,coveralls
    - python: "2.6"
      env: TOXENV=py34,coveralls
    - python: "2.7"
      env: TOXENV=py26,coveralls
    - python: "2.7"
      env: TOXENV=py34,coveralls
    - python: "3.4"
      env: TOXENV=py26,coveralls
    - python: "3.4"
      env: TOXENV=py27,coveralls
before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a
install:
  - pip install tox
script:
  - tox -e $TOXENV
notifications:
  email:
    on_success: never
    on_failure: always

